/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rockyrecovery;

public class RecoveryApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new RecoveryApp().getGreeting());
    }
}
